name: untitled1
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

dependencies:
  args: ^2.5.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shelf_cors_headers: ^0.1.5
  sqlite3: ^2.4.3
  path: ^1.9.0
  intl: ^0.19.0
  logging: ^1.2.0

dev_dependencies:
  http: ^1.2.1
  lints: ^4.0.0
  test: ^1.25.5
  freezed: ^2.5.2
  build_runner: ^2.4.10
  json_serializable:

